package recursion.subsequences

import java.util.Collections

/**
 * ============================================================================
 * PROBLEM: Subset Sums (Subset Sum I)
 * DIFFICULTY: Medium
 * CATEGORY: Recursion / Subsequences
 * ============================================================================
 *
 * PROBLEM STATEMENT:
 * Given a list arr of N integers, print sums of all subsets in it.
 * Output should be printed in increasing order of sums.
 *
 * INPUT FORMAT:
 * - An integer array `arr`
 *
 * OUTPUT FORMAT:
 * - A list of integers representing sums of all subsets, sorted in ascending order.
 *
 * CONSTRAINTS:
 * - 1 <= N <= 15
 * - 0 <= arr[i] <= 1000
 */

/**
 * ============================================================================
 * APPROACH & INTUITION
 * ============================================================================
 *
 * INTUITION:
 * A subset can be generated by making a choice for each element: either include
 * it in the sum or exclude it. We can traverse all possible subsets using recursion.
 *
 * ALGORITHM STEPS:
 * 1. Function `findSubsetSums(index, currentSum)`.
 * 2. Base Case: If `index == N`:
 *    - Add `currentSum` to result list.
 *    - Return.
 * 3. Recursive Steps:
 *    - Pick: `findSubsetSums(index + 1, currentSum + arr[index])`
 *    - Don't Pick: `findSubsetSums(index + 1, currentSum)`
 * 4. Finally, sort the result list.
 *
 * COMPLEXITY ANALYSIS:
 * - Time Complexity: O(2^N)
 * - Space Complexity: O(2^N) to store the sums (and O(N) stack).
 */

class SubsetSumI {

    fun subsetSums(arr: IntArray): List<Int> {
        val subsetSums = ArrayList<Int>()
        findSubsetSums(0, 0, arr, subsetSums)
        Collections.sort(subsetSums)
        return subsetSums
    }

    private fun findSubsetSums(index: Int, currentSum: Int, arr: IntArray, result: ArrayList<Int>) {
        if (index == arr.size) {
            result.add(currentSum)
            return
        }

        // Pick the element
        findSubsetSums(index + 1, currentSum + arr[index], arr, result)

        // Don't pick the element
        findSubsetSums(index + 1, currentSum, arr, result)
    }
}

fun main() {
    val solver = SubsetSumI()

    // Test Case 1: [2, 3]
    println("Test Case 1: [2, 3]")
    println(solver.subsetSums(intArrayOf(2, 3)))
    // Expected: [0, 2, 3, 5]

    // Test Case 2: [5, 2, 1]
    println("\nTest Case 2: [5, 2, 1]")
    println(solver.subsetSums(intArrayOf(5, 2, 1)))
    // Expected: [0, 1, 2, 3, 5, 6, 7, 8]

    // Test Case 3: []
    println("\nTest Case 3: []")
    println(solver.subsetSums(intArrayOf()))
    // Expected: [0]
}
